# Trigger pipeline on commits to main
trigger:
- main

pool:
  vmImage: 'Default'

variables:
  # Replace with your ACR name (without .azurecr.io)
  ACR_NAME: 'aksrg'
  IMAGE_NAME: 'pharma'
  TAG: $(Build.BuildId) # Use build ID for tagging images

steps:
# Step 1: Checkout code
- task: Checkout@1

# Step 2: Set up Node.js
- task: UseNode@1
  inputs:
    version: '16.x' # Specify Node.js version

# Step 3: Install dependencies and build
- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'


# Step 5: Build Docker image
- task: Docker@2
  inputs:
    command: build
    containerRegistry: 'acr-serviceconnection'
    repository: 'Nehalkhan729'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)

# Step 6: Push Docker image to ACR
- task: Docker@2
  inputs:
    command: push
    tags: |
      $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
      $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
