trigger:
  - main

pool:
  name: Default
  demands: agent.name
  vmImage: 'ubuntu-latest'

stages:
  - stage: Nodejs
    displayName: Set Up NodeJs
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '16.x'
              checkLatest: true
            displayName: 'Set Up NodeJS'

          - script: npm install
            displayName: 'Install Dependencies'

          - script: npm run build
            displayName: 'Build Project'

          # Step 4: Grant Docker Permissions
          - script: |
              sudo usermod -aG docker $(whoami)
              sudo chown $USER:$USER /var/run/docker.sock
            displayName: 'Grant Docker Permissions'  

          # Step 4: Log in to Docker Hub
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: 'Dockerconnection'  # Replace with your Docker Hub service connection name
            displayName: 'Log in to Docker Hub'

          # Step 5: Build the Docker image
          - task: Docker@2
            inputs:
              command: build
              Dockerfile: 'Dockerfile'  # Ensure the path to your Dockerfile is correct
              repository: 'nehalkhan729/pharma'  # Replace with your Docker Hub repo
              tags: |
                $(Build.BuildId)
                latest
            displayName: 'Build Docker Image'

          # Step 6: Push the Docker image to Docker Hub
          - task: Docker@2
            inputs:
              command: push
              repository: 'nehalkhan729/pharma'  # Replace with your Docker Hub repo
              tags: |
                $(Build.BuildId)
                latest
            displayName: 'Push Docker Image to Docker Hub'
